package:
  name: vmtk
  version: "v1.4"

source:
  fn: vmtk-1.4-beta.3.tar.gz
  url: https://github.com/vmtk/vmtk/archive/v1.4-beta.3.tar.gz

requirements:
  build:
    - python
    - future
    - cmake >= 3.8
    - git

  run:
    - python
    - future

about:
  home: www.vmtk.org
  license: "See http://www.vmtk.org/license.html"
  summary: " vmtk - the Vascular Modeling Toolkit. See www.vmtk.org/ for details. "

